---- MODULE MC ----
EXTENDS new_raft, TLC

spec ==
Spec
----

inv_Inv ==
Inv
----

CONSTANTS
s1, s2, s3
const_Server ==
{s1, s2, s3}
----

CONSTANTS
v1, v2
const_Value ==
{v1, v2}
----

symm_2 ==
Permutations(const_Server) \union Permutations(const_Value)
====================
\* Generated by tlcwrapper.py on 2022-03-30 21:10:31.229447
